#!/bin/bash

#
# Openbox autostart script for Semplice Linux.
# (C) 2009-2013 The Semplice Linux Team. All rights reserved.
# Released under the terms of the GNU GPL v3 license (or later). See /usr/share/common-licenses/GPL.
#

### Set variables, if they are blank...

[ -z "$icons" ] && icons="n"
if [ "$icons" = "y" ]; then
 pcmanfm_args="$pcmanfm_args --desktop"
else
 pcmanfm_args="$pcmanfm_args"
fi

# Who needs volti? (volume control on Semplice 3.x or lower)
# (if someone really needs it, just use the full executable path)
[ -z "$volcontrol" ] || [ "$volcontrol" = "volti" ] && volcontrol="volumeicon"
[ -z "$conkyconf" ] && conkyconf="/etc/conky/semplice.conf"

[ -z "$panel" ] && panel="tint2"
# $panel_config can be blank.

[ -z "$checktouchpad" ] && checktouchpad="y"
[ -z "$fixtouchpad" ] && fixtouchpad="n"

[ -z "$interval" ] && interval="2"

if [ -e "/etc/semplice-live-mode" ]; then
	export LIVEMODE="`cat /etc/semplice-live-mode`"
fi

### LIVE SYSTEM 

# Fix keyboard, not useful in "yeahh", needed to fix layout in "install" (and, of course, needed by "nolock")

if [ "$LIVEMODE" ]; then # The code below permits to resolve a "bug" in the live session in build 40 and higher.
	. /etc/default/keyboard
	if [[ "$XKBMODEL" ]]; then
		setxkbmap $XKBLAYOUT -model $XKBMODEL
	else
		setxkbmap $XKBLAYOUT
	fi
fi

if [ "$LIVEMODE" = "yeahh" ]; then
	nitrogen --set-centered /usr/share/images/desktop-base/semplice_gdm_background.png
	sudo /usr/bin/keeptalking_gtk.py
	#sudo invoke-rc.d hal restart
	sudo screen -A -m -d -S gdm3 nice /usr/share/keeptalking/restartgdm lightdm
elif [ "$LIVEMODE" = "install" ]; then
	nitrogen --set-centered /usr/share/images/desktop-base/semplice_gdm_background.png
	#roxterm --hide-menubar -f -T "Install Semplice" -n "Semplice Live System Installer" -e /usr/bin/linstaller_wrapper.sh start
	/usr/bin/linstaller_crash_wrapper.sh start -f=glade # use GUI
	# If install fails, let the user choose: Or reboot or continue to boot the live system
	semplice-logout --reboot-install
	echo "nolock" | sudo tee /etc/semplice-live-mode
elif [ "$LIVEMODE" = "install-raspberrypi" ]; then
	nitrogen --set-centered /usr/share/images/desktop-base/semplice_gdm_background.png
	#roxterm --hide-menubar -f -T "Install Semplice" -n "Semplice Live System Installer" -e /usr/bin/linstaller_wrapper.sh start -c=semplice-raspberrypi
	/usr/bin/linstaller_crash_wrapper.sh start -c=semplice-raspberrypi -f=glade # use GUI
	sudo reboot
fi

[ "$LIVEMODE" = "yeahh" ] && exit 0 # All ends here if yeahh.

### Ok, begin... ;-)

# Workaround to get 'Applications' bookmark work in pcmanfm
export XDG_MENU_PREFIX="gnome-"

## OLD WORKAROUND TO GET NOTIFICATIONS WORKING:
# An update to notification-daemon dropped the old way to launch it (via dbus) in favour of a XDG .desktop autostart way.
# This forces semplice (openbox-xdg-autostart in fact, which is started before this script and it's not controlled by us) to launch notification-daemon.
# This means that the fancy notifications (notify-osd) are not started.
# Boxes who have xfce4-notify will not get it started starting from semplice-utilities 2.10.4.
#
# We should *KILL* (yeah, kill) the notification-daemon.
#kill -9 `pidof /usr/lib/notification-daemon/notification-daemon`
# And then start notify-osd.
#/usr/lib/notify-osd/notify-osd &
## END OF WORKAROUND

## NEW WORKAROUND TO GET NOTIFICATIONS WORKING:
# As of Semplice 3.0 RC1, we are now using xfce4-notifyd. It should be launched automatically via dbus, but we need
# before to kill notification-daemon if it is runnng.
#
NOTIPID="`pidof /usr/lib/notification-daemon/notification-daemon`"
if [ $NOTIPID ]; then
	kill -9 $NOTIPID
fi
#
## END OF WORKAROUND

# Check if a touchpad is connected... checktouchpad="n" and fixtouchpad="y" forces this.
if [ "$checktouchpad" = "y" ] && [ "`grep -i touchpad /proc/bus/input/devices`" ]; then
	fixtouchpad="y"
elif [ "$checktouchpad" = "y" ]; then
	fixtouchpad="n"
fi
# Enable tap-to-click, many thanks to Carmine Sorrentino <http://debianaro.posterous.com> for that!
if [ "$fixtouchpad" = "y" ]; then
	synclient TapButton1=1
	synclient TapButton2=2
	synclient TapButton3=2
	synclient VertTwoFingerScroll=1
	synclient HorizTwoFingerScroll=1
	synclient VertEdgeScroll=1
fi

# Set nitrogen config...
if [ -e "$HOME/.config/nitrogen/nitrogen.cfg.firststart" ]; then
 echo "dirs=$HOME/.config/nitrogen/add-wallpaper;/usr/share/backgrounds;" >> $HOME/.config/nitrogen/nitrogen.cfg.firststart
 mv $HOME/.config/nitrogen/nitrogen.cfg.firststart $HOME/.config/nitrogen/nitrogen.cfg
fi

# Start panel, conky, volume control and composite manager
(sleep $interval

$panel $panel_config &
[ "$conkyconf" != "disabled" ] && conky --config $conkyconf &

[ "$volcontrol" != "disabled" ] && $volcontrol &

[ -e ~/.config/.composite_enabled ] && [ -x /usr/bin/compton ] && /usr/bin/compton -b
) &

xscreensaver &

# Autostaring applications in /etc/xdg/autostart and ~/.config/autostart:
xdg-autostart GNOME XFCE LXDE # XFCE is needed for xfce4-power manager, LXDE for lxrandr.

# File Manager
pcmanfm -d $pcmanfm_args &
[ "$icons" = "n" ] && nitrogen --restore # If no icons, set wallpaper ourself.

# And tell the user that all is OK! ;)
#notify-send -i config-users "Successfully logged in" "Welcome to your Semplice desktop, $USER!"
